modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/NotRyken/XaeroZoomout/issues"
displayURL = "https://modrinth.com/mod/xaero-zoom-out"
license = "MIT"

[[mods]]
modId = "xaerozoomout"
version = "${version}"
displayName = "Xaero Zoomout"
authors = "NotRyken"
description = "Reduces the minimum zoom of Xaeros's World Map from 0.0625x to 0.0025x"
logoFile = "icon.png"

[[dependencies.xaerozoomout]]
modId = "forge"
mandatory = true
versionRange = "[41.0.15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xaerozoomout]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xaerozoomout]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[1.34.1,)"
ordering = "NONE"
side = "BOTH"