modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issues_url}" #optional: none

[[mods]]
  modId="${mod_id}"
  version="${version}" #optional: "1"
  displayName="${mod_name}" #optional: modId
  description='''${mod_description}''' # optional: "MISSING DESCRIPTION"
  logoFile="icon.png" #optional: none
  features={ java_version="[17,)" }
  credits="${mod_credits}" #optional: none
  authors="${mod_author}" #optional: none
  displayURL="${homepage_url}" #optional: none

[[mixins]]
  config="commandkeys.mixins.json"
[[mixins]]
  config="commandkeys.forge.mixins.json"

[[dependencies.${mod_id}]]
  modId="xaerosworldmap"
  mandatory=false
  versionRange="[${xwm_forge_version},)"
  ordering="NONE" #optional: "NONE"
  side="CLIENT" #optional: "BOTH"

[[dependencies.${mod_id}]] #optional
  modId="forge"
  mandatory=true
  versionRange="${forge_version_range}"
  ordering="NONE" #optional: "NONE"
  side="CLIENT" #optional: "BOTH"

[[dependencies.${mod_id}]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE" #optional: "NONE"
  side="BOTH" #optional: "BOTH"

# https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/
# https://docs.minecraftforge.net/en/latest/misc/updatechecker/
# https://files.minecraftforge.net/
